# Decap CMS Config
backend:
  name: "git-gateway"
  branch: "main" 


media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "./src/_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "vehicles"
    label: "Vehicles"
    folder: "./src/vehicles/vehicle"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Vehicle Name", name: "name", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

      